
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heozxmzglhrbrzpsvbrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhlb3p4bXpnbGhyYnJ6cHN2YnJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzIyNTksImV4cCI6MjA2MTQ0ODI1OX0.WDib-BNHRslc7c1wTRdzufT23mCpM-TBhA_CpyxMln4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Transaction functions
export const beginTransaction = async () => {
  try {
    return await supabase.rpc('begin_transaction');
  } catch (error) {
    console.error('Error beginning transaction:', error);
    return { error };
  }
};

export const commitTransaction = async () => {
  try {
    return await supabase.rpc('commit_transaction');
  } catch (error) {
    console.error('Error committing transaction:', error);
    return { error };
  }
};

export const rollbackTransaction = async () => {
  try {
    return await supabase.rpc('rollback_transaction');
  } catch (error) {
    console.error('Error rolling back transaction:', error);
    return { error };
  }
};
